### ISSUE TITLE
Training on own data

### ISSUE THREAD

**Issue by shanpriya3** [zEttOn86/3D-Unet#3]
Hi, I would like to train it on my own dataset in nifty format. I modified the training, testing and validation sets and the path. Mine is two class segmentation problem and I modified number of classes to 2. But I am getting error while doing so. While training on your dataset I didn’t get any errors. Should I modify anything else in the base.yml?

**Comment by zEttOn86** [comment]
Thank you for reply.
Hmm, Could you show me your error?

**Comment by shanpriya3** [comment]
Hi, thanks for your response. Here is the screenshot of the error.

![Screenshot from 2020-01-06 15-13-17](https://user-images.githubusercontent.com/26112565/71823391-615e8200-3097-11ea-8a06-3c6b810c6945.png)

**Comment by zEttOn86** [comment]
Hi, thank you for your response.

This error is in `dataset.py` at line 64.
https://github.com/zEttOn86/3D-Unet/blob/master/dataset.py#L64

I guess z slice size of your image is smaller than `self._patch_side` (default is 64 that is set in `configs/base.yml`).

So first of all, please check your z slice size.
If it is right, please change `dataset.py` at line 64 and 65 as follow:

```python
- z_s = np.random.randint(0, d-self._patch_side)
- z_e = z_s+self._patch_side
+ smaller_patchside = XX # XX < your z slice
+ z_s = np.random.randint(0, d-smaller_patchside)
+ z_e = z_s+smaller_patchside
```

I start to learn English recently xD.
If you cant understand my English, please feel free to ask me any questions.

**Comment by shanpriya3** [comment]
Hi, Thanks for your quick response :)

Yes, I have varying z slice sizes ranging from 31 to 115. So, can I set the value of XX= 24? 
Is it necessary to have the isotropic scaling?

**Comment by zEttOn86** [comment]
Hi
Yes you can set 24 for XX.
If you set that value, probably this program work.
You must be set XX lower than 32 in your dataset .

> Is it necessary to have the isotropic scaling?

Its difficult question to answer, since it depends on what you want.

I think its not necessary, if you want just to work this program.

But probably its necessary, if you want to train U-Net while cosidering image spacing.

**Comment by shanpriya3** [comment]
Hi, I have this new issue. I am training it on dataset with two labels.
![image](https://user-images.githubusercontent.com/26112565/74342027-16780e80-4da9-11ea-9d09-41bb24a94bad.png)

**Comment by shanpriya3** [comment]
It works fine while using high computing machine.

**Comment by shanpriya3** [comment]
Hi, I have trained the model and I want to use the trained model to get the segmentation for the volumes for which I don't have a ground truth data. How to do so?

**Comment by zEttOn86** [comment]
Hi, 
If I were you, I annotate the volume using 3D slicer...

**Comment by shanpriya3** [comment]
Thanks.
While prediction, I am getting the following error.
![image](https://user-images.githubusercontent.com/26112565/75797290-3d58ad80-5d75-11ea-9e90-ddf55d11c1bb.png)
I should use snapshot_iter_40000.npz as model, right? While using UNet3D_40000.npz, I am getting predictions for the labels. What is the difference between these two?

**Comment by zEttOn86** [comment]
Hi!
you use UNet3D_40000.npz for predictions.
For snapshot_iter_40000.npz, it is use to train model from middle.

snapshot_iter_40000.npz contains as below:
- Type of Updater
- Iterations
- Parameters of model
etc...

while  UNet3D_40000.npz , it includes only parameters of model.

**Comment by shanpriya3** [comment]
Hi,
Thanks. It works. I have couple of questions. 
1. Regarding the dice score for the prediction, Is it possible to get the dice score for the test images.
2. Regarding the dice score plot you have shown, for some iterations it is almost  zero and the plot is not smooth. Is there a specific reason.
3. How to cite your work?

**Comment by zEttOn86** [comment]
> Regarding the dice score for the prediction, Is it possible to get the dice score for the test images.

Yes, it is.
Please use [3D-Unet/evaluations/calc_ji.py](https://github.com/zEttOn86/3D-Unet/blob/master/evaluations/calc_ji.py)
This code calc Jaccard index, so you can calc dice score using relationship between dice score and j.i. 
It follows as below:

<a href="https://www.codecogs.com/eqnedit.php?latex=\\&space;J.I.=\frac{D.S.}{2-D.S.}&space;\\&space;\\&space;D.S.=\frac{2J.I.}{J.I.&plus;1}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\\&space;J.I.=\frac{D.S.}{2-D.S.}&space;\\&space;\\&space;D.S.=\frac{2J.I.}{J.I.&plus;1}" title="\\ J.I.=\frac{D.S.}{2-D.S.} \\ \\ D.S.=\frac{2J.I.}{J.I.+1}" /></a>

- [ref.](https://stats.stackexchange.com/questions/238684/what-are-the-difference-between-dice-jaccard-and-overlap-coefficients)


>Regarding the dice score plot you have shown, for some iterations it is almost zero and the plot is not smooth. Is there a specific reason.

In this case,  I only validated some patches, and validated patch is different at each iterations, so dice is not smooth .
There are any patch which included only background, and i dont calc dice score of background area, so dice is zero.


> How to cite your work?

This LICENCE is MIT. so no need to cite this.

**Comment by shanpriya3** [comment]
Thanks for the explanation. On my data, I am getting a dice plot as below.  The dice values are not zero but still, there is a fluctuation in the dice scores. For example, for 35000 iterations there is a sudden drop in the dice score. I am not sure about the reason.

![image](https://user-images.githubusercontent.com/26112565/76208968-0ebd5580-6201-11ea-8abc-d2843d1388ed.png)

**Comment by zEttOn86** [comment]
I'm sorry that replied so late.
Hmm..., its a difficult question.
I think [this post](https://stats.stackexchange.com/questions/321460/dice-coefficient-loss-function-vs-cross-entropy) is useful.

**Comment by chenjingyi-star** [comment]
After fixing the header file ,report the following error:
![1](https://user-images.githubusercontent.com/65766289/83858392-ff41a000-a74e-11ea-879d-e0eca4a5c988.png)


Learning Rate: 0.0001

 Initilaze dataset 
    # of cases: 10
   Org   from: t1/xIBSR/06/fxIBSR_06_ana.nii.gz
   label from: seg/fmask06.nii.gz
Traceback (most recent call last):
  File "train.py", line 156, in <module>
    main()
  File "train.py", line 59, in main
    config.unet['number_of_label'])
  File "/home/customer/桌面/my3DUnet/dataset.py", line 46, in __init__
    label[np.arange(org.shape[1]*org.shape[2]*org.shape[3]), label_] = 1
IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by chenjingyi-star** [comment]
Hello,don't worry about my mistakes,I have solved these problems.

**Comment by chenjingyi-star** [comment]
Which public dataset is your dataset or your own dataset?
